# Generated by Django 5.1.3 on 2024-11-13 12:08

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='count_quiz',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='users',
            name='event_datetime',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
